name: Issue greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ğŸ‘‹ Hello @${{ github.actor }}, thank you for your interest in make-sense - free to use online tool for labelling photos! ğŸ·ï¸

            ## ğŸ Bug reports

            If you noticed that make-sense is not working properly, please provide us with as much information as possible. To make your life easier, we have prepared a **bug report template** containing all the relevant details. We know, we ask for a lot... However, please believe that knowing all that extra information - like the type of browser you use or the version of node you have installed - really helps us to solve your problems faster and more efficiently. ğŸ˜‰

            ## ğŸ’¬ Get in touch

            If you've been trying to contact us but for some reason we haven't responded to your issue yet, don't hesitate to get back to us on [Gitter](https://gitter.im/make-sense-ai/community) or [Twitter](https://twitter.com/PiotrSkalski92).

            ## ğŸ’» Local setup

            ```bash
            # clone repository
            git clone https://github.com/SkalskiP/make-sense.git

            # navigate to main dir
            cd make-sense

            # install dependencies
            npm install

            # serve with hot reload at localhost:3000
            npm start
            ```
            To ensure proper functionality of the application locally, an npm `8.x.x` and node.js `v16.x.x` versions are required. More information about this problem is available in the [#16](https://github.com/SkalskiP/make-sense/issues/16) issue.

